development:
  adapter: postgresql
  encoding: utf8
  database: bid_site_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: bid_site_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: bid_site_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
